# Azure Developer CLI (azd) configuration file
# yaml-language-server: $schema=https://aka.ms/azure-dev-schema

name: secure-databricks-azureml
metadata:
  template: secure-databricks-azureml@0.0.1-beta
  description: Secure Azure Databricks with Unity Catalog, Azure ML, and AI Foundry

# Infra configuration
infra:
  provider: bicep
  path: infra
  module: main

# Pipeline configuration (for CI/CD integration)
pipeline:
  provider: azdo

# Hook configuration - Deployment automation
hooks:
  # Pre-provision: Validation and setup
  preprovision:
    shell: pwsh
    run: pwsh ./infra/scripts/validate.ps1
  
  # Post-provision: Create Unity Catalog metastore (Phase 1 complete)
  postprovision:
    shell: pwsh
    run: pwsh ./infra/scripts/postprovision.ps1
  
  # Post-deploy: Deploy UC components (Phase 2 complete)
  postdeploy:
    shell: pwsh
    run: pwsh ./infra/scripts/postdeploy.ps1
