# Azure Developer CLI (azd) configuration file
# yaml-language-server: $schema=https://aka.ms/azure-dev-schema

name: secure-databricks-azureml
metadata:
  template: secure-databricks-azureml@0.0.1-beta

# Infra configuration
infra:
  provider: bicep
  path: infra
  module: main

# Pipeline configuration
pipeline:
  provider: azdo

# Hook configuration
hooks:
  preprovision:
    shell: pwsh
    run: |
      Write-Host "Validating deployment configuration..." -ForegroundColor Green
  
  postdeploy:
    shell: pwsh
    run: |
      Write-Host "========================================" -ForegroundColor Green
      Write-Host "Deploying Terraform Unity Catalog" -ForegroundColor Green
      Write-Host "========================================" -ForegroundColor Green
      Write-Host ""
      ./infra/scripts/postdeploy.ps1
