#!/bin/bash
set -e

echo "========================================================"
echo "Post-Provision: Deploying Terraform UC Layer"
echo "========================================================"
echo ""

# Get outputs from Bicep deployment
echo "Retrieving Bicep deployment outputs..."

RESOURCE_GROUP=$AZURE_RESOURCE_GROUP
SUBSCRIPTION_ID=$(az account show --query id -o tsv)

# Get Databricks workspace details from resource group
DATABRICKS_WORKSPACE=$(az resource list \
  --resource-group "$RESOURCE_GROUP" \
  --resource-type "Microsoft.Databricks/workspaces" \
  --query "[0]" -o json)

DATABRICKS_WORKSPACE_ID=$(echo "$DATABRICKS_WORKSPACE" | jq -r '.id')
DATABRICKS_WORKSPACE_NAME=$(echo "$DATABRICKS_WORKSPACE" | jq -r '.name')

# Extract workspace host URL
WORKSPACE_REGION=$(echo "$DATABRICKS_WORKSPACE" | jq -r '.location')
WORKSPACE_HOST="https://${DATABRICKS_WORKSPACE_NAME}.${WORKSPACE_REGION}.azuredatabricks.net"

echo "  ✓ Subscription ID: $SUBSCRIPTION_ID"
echo "  ✓ Workspace ID: $DATABRICKS_WORKSPACE_ID"
echo "  ✓ Workspace Host: $WORKSPACE_HOST"
echo ""

# Get Databricks account ID from environment
if [ -z "$DATABRICKS_ACCOUNT_ID" ]; then
  echo "ERROR: DATABRICKS_ACCOUNT_ID not set"
  echo ""
  echo "PowerShell: \$env:DATABRICKS_ACCOUNT_ID = \"your-account-id\""
  echo "Bash:       export DATABRICKS_ACCOUNT_ID=\"your-account-id\""
  echo ""
  echo "Get your account ID from: https://accounts.azuredatabricks.net"
  exit 1
fi

echo "Initializing Terraform..."
cd terraform

# Create terraform.tfvars if not exists
if [ ! -f terraform.tfvars ]; then
  echo "Creating terraform.tfvars from environment..."
  cat > terraform.tfvars <<EOF
# Auto-generated by azd postprovision
subscription_id                = "$SUBSCRIPTION_ID"
azure_region                   = "$WORKSPACE_REGION"
environment_name               = "${ENVIRONMENT_NAME:-dev}"
project_name                   = "${PROJECT_NAME:-databricks}"
shared_resource_group_name     = "$RESOURCE_GROUP"
databricks_workspace_id        = "$DATABRICKS_WORKSPACE_ID"
databricks_workspace_host      = "$WORKSPACE_HOST"
databricks_account_id          = "$DATABRICKS_ACCOUNT_ID"
metastore_storage_name         = "adbmetastore${RANDOM}"
metastore_name                 = "uc_metastore_${ENVIRONMENT_NAME:-dev}"
access_connector_name          = "adb-access-connector"
EOF
  echo "  ✓ Created terraform.tfvars"
else
  echo "  ✓ Using existing terraform.tfvars"
fi

echo ""
echo "Running: terraform init..."
terraform init -upgrade

echo ""
echo "Running: terraform plan..."
terraform plan -out=tfplan

echo ""
read -p "Review plan above. Continue with apply? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Running: terraform apply..."
  terraform apply tfplan
  echo ""
  echo "========================================================"
  echo "✓ Terraform UC deployment completed successfully!"
  echo "========================================================"
else
  echo "Terraform apply cancelled by user"
  exit 0
fi

cd ..
