#!/usr/bin/env pwsh

Write-Host "========================================================" -ForegroundColor Green
Write-Host "Post-Provision: Deploying Terraform UC Layer" -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green
Write-Host ""

# Get outputs from Bicep deployment
Write-Host "Retrieving Bicep deployment outputs..." -ForegroundColor Cyan

$SUBSCRIPTION_ID = $(az account show --query id -o tsv)
Write-Host "  ✓ Subscription ID: $SUBSCRIPTION_ID" -ForegroundColor Green

# Get workspace info from azd environment variables (set by Bicep outputs)
$RESOURCE_GROUP = $env:databricksResourceGroupName
$WORKSPACE_URL = $env:databricksWorkspaceUrl

if (-not $RESOURCE_GROUP -or -not $WORKSPACE_URL) {
  Write-Host "ERROR: Missing Databricks environment variables" -ForegroundColor Red
  Write-Host "  RESOURCE_GROUP: $RESOURCE_GROUP" -ForegroundColor Red
  Write-Host "  WORKSPACE_URL: $WORKSPACE_URL" -ForegroundColor Red
  exit 1
}

# Extract workspace ID from URL (e.g., "adb-7405605886894136.16.azuredatabricks.net" -> "7405605886894136")
$WORKSPACE_URL_TRIMMED = $WORKSPACE_URL -replace "^adb-" -replace "\..*$"
$DATABRICKS_WORKSPACE_ID = $WORKSPACE_URL_TRIMMED.Split(".")[0]
$DATABRICKS_WORKSPACE_HOST = "https://$WORKSPACE_URL"

Write-Host "  ✓ Resource Group: $RESOURCE_GROUP" -ForegroundColor Green
Write-Host "  ✓ Workspace ID: $DATABRICKS_WORKSPACE_ID" -ForegroundColor Green
Write-Host "  ✓ Workspace Host: $DATABRICKS_WORKSPACE_HOST" -ForegroundColor Green

# Get workspace region
$WORKSPACE_DETAILS = $(az databricks workspace list `
  --resource-group $RESOURCE_GROUP `
  --query "[0]" -o json | ConvertFrom-Json)

$WORKSPACE_REGION = $WORKSPACE_DETAILS.location
Write-Host "  ✓ Region: $WORKSPACE_REGION" -ForegroundColor Green
Write-Host ""

# Get Databricks account ID from environment
if (-not $env:DATABRICKS_ACCOUNT_ID) {
  Write-Host "ERROR: DATABRICKS_ACCOUNT_ID not set" -ForegroundColor Red
  Write-Host ""
  Write-Host "PowerShell: `$env:DATABRICKS_ACCOUNT_ID = 'your-account-id'"
  Write-Host "Bash:       export DATABRICKS_ACCOUNT_ID='your-account-id'"
  Write-Host ""
  Write-Host "Get your account ID from: https://accounts.azuredatabricks.net"
  exit 1
}

$DATABRICKS_ACCOUNT_ID = $env:DATABRICKS_ACCOUNT_ID
Write-Host "  ✓ Account ID: $DATABRICKS_ACCOUNT_ID" -ForegroundColor Green
Write-Host ""

# Navigate to terraform environments directory (where the configuration is)
Write-Host "Initializing Terraform..." -ForegroundColor Cyan

# Get the project root (2 levels up from this script: scripts -> infra -> root)
$PROJECT_ROOT = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$TERRAFORM_DIR = Join-Path $PROJECT_ROOT "terraform" "environments"

Write-Host "  Script Root: $PSScriptRoot" -ForegroundColor Cyan
Write-Host "  Project Root: $PROJECT_ROOT" -ForegroundColor Green
Write-Host "  Terraform Dir: $TERRAFORM_DIR" -ForegroundColor Green

if (-not (Test-Path $TERRAFORM_DIR)) {
  Write-Host "ERROR: Terraform directory not found: $TERRAFORM_DIR" -ForegroundColor Red
  exit 1
}

Push-Location $TERRAFORM_DIR

# Create terraform.tfvars (always recreate to ensure correct values)
Write-Host "Creating terraform.tfvars with current values..."

$tfvars = @"
# Auto-generated by azd postdeploy
subscription_id                = "$SUBSCRIPTION_ID"
azure_region                   = "$WORKSPACE_REGION"
environment_name               = "$($env:ENVIRONMENT_NAME ?? 'dev')"
project_name                   = "$($env:PROJECT_NAME ?? 'databricks')"
shared_resource_group_name     = "$RESOURCE_GROUP"
databricks_workspace_id        = "$DATABRICKS_WORKSPACE_ID"
databricks_workspace_host      = "$DATABRICKS_WORKSPACE_HOST"
databricks_account_id          = "$DATABRICKS_ACCOUNT_ID"
metastore_storage_name         = "adbmetastore$(Get-Random -Maximum 9999 -Minimum 1000)"
metastore_name                 = "uc_metastore_$($env:ENVIRONMENT_NAME ?? 'dev')"
access_connector_name          = "ac-databricks-$($env:ENVIRONMENT_NAME ?? 'dev')-uc"
"@

Set-Content -Path "terraform.tfvars" -Value $tfvars
Write-Host "  ✓ Created terraform.tfvars" -ForegroundColor Green
Write-Host "    - Workspace ID: $DATABRICKS_WORKSPACE_ID" -ForegroundColor Cyan

Write-Host ""
Write-Host "Cleaning Terraform cache..." -ForegroundColor Cyan
Remove-Item -Path ".terraform" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path "*.tfstate*" -Force -ErrorAction SilentlyContinue

Write-Host "Running: terraform init..." -ForegroundColor Cyan
terraform init -upgrade

Write-Host ""
Write-Host "Running: terraform plan..." -ForegroundColor Cyan
terraform plan -out=tfplan

Write-Host ""
Write-Host "Running: terraform apply (auto-approved)..." -ForegroundColor Cyan
terraform apply -auto-approve tfplan

Write-Host ""
Write-Host "========================================================" -ForegroundColor Green
Write-Host "✓ Terraform UC deployment completed successfully!" -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green

Pop-Location
