#!/usr/bin/env pwsh

Write-Host "========================================================" -ForegroundColor Green
Write-Host "Post-Provision: Deploying Terraform UC Layer" -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green
Write-Host ""

# Get outputs from Bicep deployment
Write-Host "Retrieving Bicep deployment outputs..." -ForegroundColor Cyan

$SUBSCRIPTION_ID = $(az account show --query id -o tsv)
Write-Host "  ✓ Subscription ID: $SUBSCRIPTION_ID" -ForegroundColor Green

# Find Databricks workspace (search all resource groups)
Write-Host "  Searching for Databricks workspace..."
$DATABRICKS_WORKSPACE = $(az resource list `
  --subscription $SUBSCRIPTION_ID `
  --resource-type "Microsoft.Databricks/workspaces" `
  --query "[0]" -o json | ConvertFrom-Json)

if (-not $DATABRICKS_WORKSPACE) {
  Write-Host "ERROR: No Databricks workspace found in subscription" -ForegroundColor Red
  exit 1
}

$RESOURCE_GROUP = $DATABRICKS_WORKSPACE.resourceGroup
$DATABRICKS_WORKSPACE_ID = $DATABRICKS_WORKSPACE.id
$DATABRICKS_WORKSPACE_NAME = $DATABRICKS_WORKSPACE.name

# Extract workspace host URL
$WORKSPACE_REGION = $DATABRICKS_WORKSPACE.location
$WORKSPACE_HOST = "https://$($DATABRICKS_WORKSPACE_NAME).$($WORKSPACE_REGION).azuredatabricks.net"

Write-Host "  ✓ Resource Group: $RESOURCE_GROUP" -ForegroundColor Green
Write-Host "  ✓ Workspace ID: $DATABRICKS_WORKSPACE_ID" -ForegroundColor Green
Write-Host "  ✓ Workspace Name: $DATABRICKS_WORKSPACE_NAME" -ForegroundColor Green
Write-Host "  ✓ Workspace Host: $WORKSPACE_HOST" -ForegroundColor Green
Write-Host "  ✓ Region: $WORKSPACE_REGION" -ForegroundColor Green
Write-Host ""

# Get Databricks account ID from environment
if (-not $env:DATABRICKS_ACCOUNT_ID) {
  Write-Host "ERROR: DATABRICKS_ACCOUNT_ID not set" -ForegroundColor Red
  Write-Host ""
  Write-Host "PowerShell: `$env:DATABRICKS_ACCOUNT_ID = 'your-account-id'"
  Write-Host "Bash:       export DATABRICKS_ACCOUNT_ID='your-account-id'"
  Write-Host ""
  Write-Host "Get your account ID from: https://accounts.azuredatabricks.net"
  exit 1
}

$DATABRICKS_ACCOUNT_ID = $env:DATABRICKS_ACCOUNT_ID
Write-Host "  ✓ Account ID: $DATABRICKS_ACCOUNT_ID" -ForegroundColor Green
Write-Host ""

# Navigate to terraform environments directory (where the configuration is)
Write-Host "Initializing Terraform..." -ForegroundColor Cyan
Push-Location "terraform/environments"

# Create terraform.tfvars if not exists
if (-not (Test-Path "terraform.tfvars")) {
  Write-Host "Creating terraform.tfvars from environment..."
  
  $tfvars = @"
# Auto-generated by azd postprovision
subscription_id                = "$SUBSCRIPTION_ID"
azure_region                   = "$WORKSPACE_REGION"
environment_name               = "$($env:ENVIRONMENT_NAME ?? 'dev')"
project_name                   = "$($env:PROJECT_NAME ?? 'databricks')"
shared_resource_group_name     = "$RESOURCE_GROUP"
databricks_workspace_id        = "$DATABRICKS_WORKSPACE_ID"
databricks_workspace_host      = "$WORKSPACE_HOST"
databricks_account_id          = "$DATABRICKS_ACCOUNT_ID"
metastore_storage_name         = "adbmetastore$(Get-Random -Maximum 9999 -Minimum 1000)"
metastore_name                 = "uc_metastore_$($env:ENVIRONMENT_NAME ?? 'dev')"
access_connector_name          = "adb-access-connector"
"@
  
  Set-Content -Path "terraform.tfvars" -Value $tfvars
  Write-Host "  ✓ Created terraform.tfvars" -ForegroundColor Green
} else {
  Write-Host "  ✓ Using existing terraform.tfvars" -ForegroundColor Green
}

Write-Host ""
Write-Host "Running: terraform init..." -ForegroundColor Cyan
terraform init -upgrade

Write-Host ""
Write-Host "Running: terraform plan..." -ForegroundColor Cyan
terraform plan -out=tfplan

Write-Host ""
Write-Host "Running: terraform apply (auto-approved)..." -ForegroundColor Cyan
terraform apply -auto-approve tfplan

Write-Host ""
Write-Host "========================================================" -ForegroundColor Green
Write-Host "✓ Terraform UC deployment completed successfully!" -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green

Pop-Location
