#!/usr/bin/env pwsh

Write-Host "========================================================" -ForegroundColor Green
Write-Host "Post-Deploy: Deploying Unity Catalog Components" -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Phase 2: Deploy UC Catalogs, Schemas, and Volumes" -ForegroundColor Cyan
Write-Host ""

# This script runs AFTER metastore creation (postprovision)
# It deploys Unity Catalog components: catalogs, schemas, tables, volumes

# Get outputs from Bicep deployment
Write-Host "Retrieving Bicep deployment outputs..." -ForegroundColor Cyan

$SUBSCRIPTION_ID = $(az account show --query id -o tsv)
Write-Host "  ✓ Subscription ID: $SUBSCRIPTION_ID" -ForegroundColor Green

# Get workspace info from azd environment variables (set by Bicep outputs)
$DATABRICKS_RESOURCE_GROUP = $env:databricksResourceGroupName
$WORKSPACE_URL = $env:databricksWorkspaceUrl

if (-not $DATABRICKS_RESOURCE_GROUP -or -not $WORKSPACE_URL) {
  Write-Host "ERROR: Missing Bicep environment variables" -ForegroundColor Red
  Write-Host "  DATABRICKS_RESOURCE_GROUP: $DATABRICKS_RESOURCE_GROUP" -ForegroundColor Red
  Write-Host "  WORKSPACE_URL: $WORKSPACE_URL" -ForegroundColor Red
  exit 1
}

# Extract workspace host
$DATABRICKS_WORKSPACE_HOST = "https://$WORKSPACE_URL"
Write-Host "  ✓ Workspace Host: $DATABRICKS_WORKSPACE_HOST" -ForegroundColor Green

# Get workspace region
$WORKSPACE_DETAILS = $(az databricks workspace list `
  --resource-group $DATABRICKS_RESOURCE_GROUP `
  --query "[0]" -o json | ConvertFrom-Json)

$WORKSPACE_REGION = $WORKSPACE_DETAILS.location
Write-Host "  ✓ Region: $WORKSPACE_REGION" -ForegroundColor Green

# Get environment name from the bicep parameter file
$BICEP_PARAMS_FILE = Join-Path $PSScriptRoot "..\main.bicepparam"
if (Test-Path $BICEP_PARAMS_FILE) {
  $BICEP_PARAMS = Get-Content $BICEP_PARAMS_FILE -Raw
  # Extract environmentName = 'dev' or "dev"
  if ($BICEP_PARAMS -match "param environmentName = '(\w+)'") {
    $ENV_NAME = $Matches[1]
    Write-Host "  ✓ Environment Name (from bicep): $ENV_NAME" -ForegroundColor Green
  } elseif ($BICEP_PARAMS -match 'param environmentName = "(\w+)"') {
    $ENV_NAME = $Matches[1]
    Write-Host "  ✓ Environment Name (from bicep): $ENV_NAME" -ForegroundColor Green
  } else {
    # Fallback: extract from AZURE_ENV_NAME
    $ENV_NAME = $env:AZURE_ENV_NAME -replace "databricks-azureml-", ""
    Write-Host "  ✓ Environment Name (from AZURE_ENV_NAME): $ENV_NAME" -ForegroundColor Yellow
  }
} else {
  # Fallback if no bicep params file
  $ENV_NAME = $env:AZURE_ENV_NAME -replace "databricks-azureml-", ""
  Write-Host "  ✓ Environment Name (from AZURE_ENV_NAME): $ENV_NAME" -ForegroundColor Yellow
}

Write-Host ""

# Navigate to terraform environments directory
Write-Host "Initializing Terraform for UC Components..." -ForegroundColor Cyan

# Get the project root (2 levels up from this script: scripts -> infra -> root)
$PROJECT_ROOT = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$TERRAFORM_DIR = Join-Path $PROJECT_ROOT "terraform" "environments"

Write-Host "  Project Root: $PROJECT_ROOT" -ForegroundColor Green
Write-Host "  Terraform Dir: $TERRAFORM_DIR" -ForegroundColor Green

if (-not (Test-Path $TERRAFORM_DIR)) {
  Write-Host "ERROR: Terraform environments directory not found: $TERRAFORM_DIR" -ForegroundColor Red
  exit 1
}

Push-Location $TERRAFORM_DIR

# Create terraform.tfvars for UC components
Write-Host "Creating UC components terraform.tfvars..."

$tfvars = @"
# Auto-generated by azd postdeploy
azure_region                = "$WORKSPACE_REGION"
environment_name            = "$ENV_NAME"
databricks_workspace_host   = "$DATABRICKS_WORKSPACE_HOST"
"@

Set-Content -Path "terraform.tfvars" -Value $tfvars
Write-Host "  ✓ Created terraform.tfvars" -ForegroundColor Green

Write-Host ""
Write-Host "Cleaning Terraform cache..." -ForegroundColor Cyan
Remove-Item -Path ".terraform" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path ".terraform.lock.hcl" -Force -ErrorAction SilentlyContinue
Remove-Item -Path "tfplan" -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Running: terraform init..." -ForegroundColor Cyan
terraform init -upgrade

Write-Host ""
Write-Host "Running: terraform plan..." -ForegroundColor Cyan
terraform plan -out=tfplan

Write-Host ""
Write-Host "Review the plan above. Press Enter to apply or Ctrl+C to cancel..."
Read-Host

Write-Host ""
Write-Host "Running: terraform apply..." -ForegroundColor Cyan
terraform apply tfplan

if ($LASTEXITCODE -eq 0) {
  Write-Host ""
  Write-Host "========================================================" -ForegroundColor Green
  Write-Host "✓ UC components deployment completed successfully!" -ForegroundColor Green
  Write-Host "========================================================" -ForegroundColor Green
} else {
  Write-Host ""
  Write-Host "========================================================" -ForegroundColor Red
  Write-Host "✗ UC components deployment failed!" -ForegroundColor Red
  Write-Host "========================================================" -ForegroundColor Red
  Pop-Location
  exit 1
}

Pop-Location
