#!/bin/bash
set -e

echo "========================================================"
echo "Post-Provision: Deploying Terraform UC Layer"
echo "========================================================"
echo ""

# Get outputs from Bicep deployment
echo "Retrieving Bicep deployment outputs..."

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
echo "  ✓ Subscription ID: $SUBSCRIPTION_ID"

# Get workspace info from azd environment variables (set by Bicep outputs)
DATABRICKS_RESOURCE_GROUP=${databricksResourceGroupName}
SHARED_RESOURCE_GROUP=${sharedResourceGroupName}
WORKSPACE_URL=${databricksWorkspaceUrl}

if [ -z "$DATABRICKS_RESOURCE_GROUP" ] || [ -z "$WORKSPACE_URL" ] || [ -z "$SHARED_RESOURCE_GROUP" ]; then
  echo "ERROR: Missing Databricks environment variables"
  echo "  DATABRICKS_RESOURCE_GROUP: $DATABRICKS_RESOURCE_GROUP"
  echo "  SHARED_RESOURCE_GROUP: $SHARED_RESOURCE_GROUP"
  echo "  WORKSPACE_URL: $WORKSPACE_URL"
  exit 1
fi

# Extract workspace ID from URL (e.g., "adb-7405605886894136.16.azuredatabricks.net" -> "7405605886894136")
WORKSPACE_URL_TRIMMED=$(echo "$WORKSPACE_URL" | sed 's/^adb-//' | sed 's/\..*//')
DATABRICKS_WORKSPACE_ID=$(echo "$WORKSPACE_URL_TRIMMED" | cut -d. -f1)
DATABRICKS_WORKSPACE_HOST="https://$WORKSPACE_URL"

echo "  ✓ Databricks Resource Group: $DATABRICKS_RESOURCE_GROUP"
echo "  ✓ Shared Resource Group: $SHARED_RESOURCE_GROUP"
echo "  ✓ Workspace ID: $DATABRICKS_WORKSPACE_ID"
echo "  ✓ Workspace Host: $DATABRICKS_WORKSPACE_HOST"

# Get workspace region
WORKSPACE_REGION=$(az databricks workspace list \
  --resource-group "$DATABRICKS_RESOURCE_GROUP" \
  --query "[0].location" -o tsv)
echo "  ✓ Region: $WORKSPACE_REGION"

# Parse storage outputs from Bicep
STORAGE_ACCOUNT_NAME=$(echo "$storageOutputs" | jq -r '.storageAccountName.value')
echo "  ✓ Storage Account: $STORAGE_ACCOUNT_NAME"

# Get environment name from the bicep parameter file (more reliable than AZURE_ENV_NAME)
BICEP_PARAMS_FILE="$SCRIPT_DIR/../main.bicepparam"
if [ -f "$BICEP_PARAMS_FILE" ]; then
  ENV_NAME=$(grep "param environmentName = " "$BICEP_PARAMS_FILE" | grep -oE "'[^']+'" | head -1 | tr -d "'")
  if [ -n "$ENV_NAME" ]; then
    echo "  ✓ Environment Name (from bicep): $ENV_NAME"
  else
    # Fallback: extract from AZURE_ENV_NAME
    ENV_NAME=$(echo "${AZURE_ENV_NAME}" | sed 's/databricks-azureml-//')
    echo "  ✓ Environment Name (from AZURE_ENV_NAME): $ENV_NAME"
  fi
else
  # Fallback if no bicep params file
  ENV_NAME=$(echo "${AZURE_ENV_NAME}" | sed 's/databricks-azureml-//')
  echo "  ✓ Environment Name (from AZURE_ENV_NAME): $ENV_NAME"
fi

# Get project name
PROJECT_NAME=${PROJECT_NAME:-dbxaml}
ACCESS_CONNECTOR_NAME="ac-${PROJECT_NAME}-${ENV_NAME}"
echo "  ✓ Access Connector: $ACCESS_CONNECTOR_NAME"
echo ""

# Get Databricks account ID from environment
if [ -z "$DATABRICKS_ACCOUNT_ID" ]; then
  echo "ERROR: DATABRICKS_ACCOUNT_ID not set"
  echo ""
  echo "PowerShell: \$env:DATABRICKS_ACCOUNT_ID = \"your-account-id\""
  echo "Bash:       export DATABRICKS_ACCOUNT_ID=\"your-account-id\""
  echo ""
  echo "Get your account ID from: https://accounts.azuredatabricks.net"
  exit 1
fi

echo "  ✓ Account ID: $DATABRICKS_ACCOUNT_ID"
echo ""

echo "Initializing Terraform..."

# Get the project root (2 levels up from this script: scripts -> infra -> root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/terraform/environments"

echo "  Script Dir: $SCRIPT_DIR"
echo "  Project Root: $PROJECT_ROOT"
echo "  Terraform Dir: $TERRAFORM_DIR"

if [ ! -d "$TERRAFORM_DIR" ]; then
  echo "ERROR: Terraform directory not found: $TERRAFORM_DIR"
  exit 1
fi

cd "$TERRAFORM_DIR"

# Create terraform.tfvars (always recreate to ensure correct values)
echo "Creating terraform.tfvars with current values..."
cat > terraform.tfvars <<EOF
# Auto-generated by azd postdeploy
subscription_id                = "$SUBSCRIPTION_ID"
azure_region                   = "$WORKSPACE_REGION"
environment_name               = "$ENV_NAME"
project_name                   = "$PROJECT_NAME"
shared_resource_group_name     = "$SHARED_RESOURCE_GROUP"
databricks_workspace_id        = "$DATABRICKS_WORKSPACE_ID"
databricks_workspace_host      = "$DATABRICKS_WORKSPACE_HOST"
databricks_account_id          = "$DATABRICKS_ACCOUNT_ID"
metastore_storage_name         = "$STORAGE_ACCOUNT_NAME"
access_connector_name          = "$ACCESS_CONNECTOR_NAME"
EOF
echo "  ✓ Created terraform.tfvars"
echo "    - Workspace ID: $DATABRICKS_WORKSPACE_ID"

echo ""
echo "Cleaning Terraform cache..."
rm -rf .terraform
rm -f *.tfstate*

# Set environment variables for Terraform Databricks provider
echo ""
echo "Setting Databricks environment variables for Terraform..."
export DATABRICKS_ACCOUNT_ID="$DATABRICKS_ACCOUNT_ID"
export DATABRICKS_HOST="https://accounts.azuredatabricks.net"  # Account-level operations
echo "  ✓ DATABRICKS_ACCOUNT_ID: $DATABRICKS_ACCOUNT_ID"
echo "  ✓ DATABRICKS_HOST: $DATABRICKS_HOST"
echo ""

echo "Running: terraform init..."
terraform init -upgrade

echo ""
echo "Running: terraform plan..."
terraform plan -out=tfplan

echo ""
echo "Running: terraform apply (auto-approved)..."
terraform apply -auto-approve tfplan

echo ""
echo "========================================================"
echo "✓ Terraform UC deployment completed successfully!"
echo "========================================================"
